server:
  port: 8080

spring:
  application:
    name: java-admin-system
  datasource:
    url: jdbc:mysql://localhost:3306/java_admin_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: kr754454968
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 55001
      database: 0
      connect-timeout: 2000ms
      timeout: 3000ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true

# Knife4j 配置
knife4j:
  enable: true